NMVW to new endpoint
netwerk-digitaal-erfgoed/network-of-terms pull request #1411
Opened 2024-08-20 10:06 UTC by rschalkrce

Switch Wereldculturen thesaurus endpoint from NDE to colonialcollections

As requested by @GertjanFi and @sdevalk

2024-08-20 11:21 UTC, ddeboer requested changes

2024-08-20 11:21 UTC, ddeboer commented on packages/network-of-terms-catalog/catalog/datasets/nmvw.jsonld
> +  "@id": "https://api.colonialcollections.nl/datasets/nmvw/thesaurus/services/thesaurus/sparql",
```suggestion
  "@id": "https://data.colonialcollections.nl/nmvw/thesaurus",
```

2024-08-20 11:21 UTC, ddeboer commented on packages/network-of-terms-catalog/catalog/datasets/nmvw.jsonld
> +      "@id": "https://api.colonialcollections.nl/datasets/nmvw/thesaurus/services/thesaurus/sparql",
```suggestion
      "@id": "https://data.colonialcollections.nl/nmvw/thesaurus/sparql",
```

2024-08-20 12:38 UTC, rschalkrce reviewed
thanks! Beter zo inderdaad

2024-08-21 10:31 UTC, merged

2024-08-21 10:32 UTC, ddeboer commented
:tada: This PR is included in version 9.10.0 :tada:

The release is available on [npm package (@latest dist-tag)](https://www.npmjs.com/package/@netwerk-digitaal-erfgoed/network-of-terms-catalog/v/9.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-09-23 12:47 UTC, ddeboer commented
:tada: This PR is included in version 5.4.0 :tada:

The release is available on [npm package (@latest dist-tag)](https://www.npmjs.com/package/@netwerk-digitaal-erfgoed/network-of-terms-query/v/5.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: